version: '3.8'

services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development  # Optional: Set Flask environment variable
    volumes:
      - .:/app  # Mount the current directory for live updates (optional)
