name: .NET

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [ Debug, Release ]
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # Step 3: Clean up old builds (PowerShell)
      - name: Clean bin and obj folders
        shell: pwsh
        run: |
          Write-Host "Cleaning up old builds..."
          Get-ChildItem -Path . -Recurse -Include bin, obj -Directory | Remove-Item -Recurse -Force

      # Step 4: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore BPR2-Desktop.sln

      # Step 5: Build the solution
      - name: Build
        run: dotnet build BPR2-Desktop.sln --no-restore --configuration ${{ matrix.configuration }}

      # Step 6: Run tests
      - name: Test
        run: dotnet test BPR2-Desktop.sln --no-build --configuration ${{ matrix.configuration }} --verbosity normal
